### PR TITLE
create ns object in the global namespace and let it contain all classes

### PR DESCRIPTION
**Pull request by DQNEO**
This PR creates a namespace hierarchy.
e.g.

```
global["ns"]["tupai"]["Application"] = Application; // tupai.Application
```

### CODE REVIEW

**Comment by deyunanhai** [comment]
I think this is unnecessary.
Because you can access it by use Package.classProvider.

**Comment by DQNEO** [comment]
I did'nt know that. Thank you for the advise.
Then how about making a alias which helps us to access classes easily
```
var tupai = Package.classProvider;
```

**Comment by deyunanhai** [comment]
You can Write it in your app.js just like
```
window.tupai = Package.classProvider;
```

**Comment by DQNEO** [comment]
Agree. Thank you for the advise.

**Pull request closed without merging**
